//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P.Proyect.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISTEMA_RECURSOS_HUMANOSEntities2 : DbContext
    {
        public SISTEMA_RECURSOS_HUMANOSEntities2()
            : base("name=SISTEMA_RECURSOS_HUMANOSEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGOS> CARGOS { get; set; }
        public virtual DbSet<DEPARTAMENTOS> DEPARTAMENTOS { get; set; }
        public virtual DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual DbSet<LICENCIA> LICENCIA { get; set; }
        public virtual DbSet<NOMINAS> NOMINAS { get; set; }
        public virtual DbSet<PERMISOS> PERMISOS { get; set; }
        public virtual DbSet<SALIDA_EMPLEADO> SALIDA_EMPLEADO { get; set; }
        public virtual DbSet<VACACIONES> VACACIONES { get; set; }
    }
}
