//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P.Proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACACIONES
    {
        public int Id_Vacaciones { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public string Correspondiente { get; set; }
        public string Comentarios { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
    }
}
